"use strict";
const $=(id)=>document.getElementById(id);const esc=(v)=>String(v??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const num=(v,d=2)=>Number(v||0).toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d});const money=(v)=>`${Number(v||0)<0?"-":""}$${num(Math.abs(Number(v||0)),2)}`;const price=(v)=>Number(v||0).toLocaleString("en-US",{maximumFractionDigits:Number(v)<1?6:2});
const duration=(s)=>{s=Math.max(0,Math.floor(Number(s)||0));return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(v=>String(v).padStart(2,"0")).join(":")};const time=(ts)=>ts?new Date(ts*1000).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",second:"2-digit",timeZone:"UTC"}):"—";
function tone(el,v){el.classList.remove("positive","negative");if(Number(v)>0)el.classList.add("positive");if(Number(v)<0)el.classList.add("negative")}
function render(s){const st=s.stats||{};$("pnl").textContent=money(st.pnl);tone($("pnl"),st.pnl);$("pnl-note").textContent=`Реализовано ${money(st.realized)} · Открыто ${money(st.unrealized)}`;$("win-rate").textContent=`${num(st.win_rate,1)}%`;$("record").textContent=`${st.wins||0} побед / ${st.losses||0} убытков`;$("profit-factor").textContent=st.profit_factor==null?"∞":num(st.profit_factor);$("trades").textContent=`${st.trades||0} закрытых сделок`;$("open-count").textContent=String(st.open||0).padStart(2,"0");$("uptime").textContent=`Работает ${duration(s.uptime)}`;$("session").textContent=s.session?`#${s.session}`:"—";$("mode").textContent=String(s.mode||"PAPER").toUpperCase();$("source-badge").textContent=`ИСТОЧНИК ${String(s.source||"—").toUpperCase()}`;$("last-update").textContent=`ОБНОВЛЕНО ${time(s.timestamp)} UTC`;
const radar=(Array.isArray(s.radar)?s.radar.slice():[]).sort((a,b)=>String(a.symbol).localeCompare(String(b.symbol)));$("symbols-count").textContent=String(radar.length);$("radar-body").innerHTML=radar.length?radar.slice(0,20).map(r=>{const flow=Number(r.imbalance??r.delta??r.flow??0);const signal=r.signal||r.status||"MONITOR";return `<tr><td class="symbol">${esc(r.symbol)}</td><td>${price(r.price??r.mid)}</td><td>${num(r.spread_pct??r.spread,3)}%</td><td class="${flow>0?"positive":flow<0?"negative":""}">${flow>0?"+":""}${num(flow,2)}</td><td><span class="signal">${esc(signal)}</span></td></tr>`}).join(""):'<tr><td colspan="5" class="empty">Инструменты ещё не получены. Идёт инициализация сканера.</td></tr>';syncHeatmapCoins(radar);
const positions=Array.isArray(s.positions)?s.positions:[];$("position-count").textContent=String(positions.length).padStart(2,"0");$("positions").innerHTML=positions.length?positions.map(p=>`<article class="position"><div><span>ИНСТРУМЕНТ</span><b class="symbol">${esc(p.symbol)} · <i class="side ${p.side==="LONG"?"positive":"negative"}">${esc(p.side)}</i></b></div><div><span>ВХОД</span><b>${price(p.entry)}</b></div><div><span>ТЕКУЩАЯ</span><b>${price(p.mark)}</b></div><div><span>СТОП / ЦЕЛЬ</span><b>${price(p.stop_price)} / ${price(p.target_price)}</b></div><div><span>НЕРЕАЛИЗ. P&L</span><b class="${Number(p.unrealized)>=0?"positive":"negative"}">${money(p.unrealized)}</b></div></article>`).join(""):'<div class="empty-block">Открытых позиций нет. Движок ищет подходящие сетапы.</div>';
const logs=Array.isArray(s.logs)?s.logs:[];$("event-count").textContent=String(logs.length).padStart(2,"0");$("logs").innerHTML=logs.length?logs.slice(0,30).map(l=>`<article class="event ${esc(String(l.level||"").toLowerCase())}"><div class="event-head"><span>${esc(l.symbol||"SYSTEM")}</span><time>${time(l.timestamp)} UTC</time></div><p>${esc(l.message)}</p></article>`).join(""):'<div class="empty-block">Событий пока нет. Здесь появится телеметрия движка.</div>';
const trades=Array.isArray(s.closed_trades)?s.closed_trades:[];$("trades-body").innerHTML=trades.length?trades.slice(0,20).map(t=>`<tr><td>${time(t.closed_at)} UTC</td><td class="symbol">${esc(t.symbol)}</td><td class="side ${t.side==="LONG"?"positive":"negative"}">${esc(t.side)}</td><td>${price(t.entry)} → ${price(t.exit)}</td><td class="${Number(t.pnl)>=0?"positive":"negative"}">${money(t.pnl)}</td><td>${esc(t.reason)}</td></tr>`).join(""):'<tr><td colspan="6" class="empty">В этой сессии нет закрытых сделок.</td></tr>';
renderDiagnostics(s.signal_diagnostics);renderSetupAnalysis(s.setup_analysis);renderCounterfactuals(s.setup_analysis?.counterfactual_summary);
$("error-banner").hidden=true;$("status-dot").className="status-dot online";$("connection-label").textContent="Связь установлена"}
const stageLabels={candidate_check:"Проверки кандидатов",qualified:"Квалифицировано",breakout:"Пробои",retest:"Ретесты",entry_attempt:"Попытки входа",entered:"Входы"};const reasonLabels={"low imbalance":"Слабый дисбаланс","no 3x tape acceleration":"Нет ускорения ленты ×3","spread expanded":"Расширенный спред","stale book":"Устаревший стакан","portfolio position limit":"Лимит позиций","daily loss circuit breaker":"Дневной стоп","loss-streak circuit breaker":"Серия убытков","setup expired before retest":"Сетап истёк до ретеста"};
function renderDiagnostics(d){const hasData=d&&Number(d.events)>0;$("diagnostics-events").textContent=`${Number(d?.events||0)} СОБЫТИЙ`;$(`diagnostics-empty`).hidden=hasData;$(`diagnostics-content`).hidden=!hasData;if(!hasData)return;const stages=d.stages||{};$("diagnostics-stages").innerHTML=Object.entries(stageLabels).map(([key,label])=>`<article class="funnel-step"><span>${esc(label)}</span><strong>${Number(stages[key]||0).toLocaleString("ru-RU")}</strong></article>`).join("");const rejections=Array.isArray(d.rejections)?d.rejections:[];$("diagnostics-rejections").innerHTML=rejections.length?rejections.map(r=>`<div class="reason-row"><span>${esc(reasonLabels[r.reason]||r.reason)}</span><b>${Number(r.count||0).toLocaleString("ru-RU")}</b></div>`).join(""):'<div class="empty-block">Отказов не зафиксировано.</div>';const a=d.averages||{};const metric=(label,value,suffix="")=>`<div class="average-item"><span>${label}</span><b>${value==null?"—":`${num(value,2)}${suffix}`}</b></div>`;$("diagnostics-averages").innerHTML=metric("Оценка",a.score,"/100")+metric("Дисбаланс",a.imbalance)+metric("Ускорение",a.acceleration,"×")+metric("Спред",a.spread,"%");const near=Array.isArray(d.near_misses)?d.near_misses:[];$("diagnostics-near").innerHTML=near.length?near.map(n=>`<div class="near-row"><span><b class="symbol">${esc(n.symbol)}</b><small>${esc(reasonLabels[n.reason]||n.reason||stageLabels[n.stage]||n.stage)} · ${time(n.timestamp)} UTC</small></span><b>${n.score==null?"—":`${n.score}/100`}</b></div>`).join(""):'<div class="empty-block">Кандидатов пока нет.</div>'}
function renderSetupAnalysis(data){const setups=Array.isArray(data?.latest)?data.latest:[],outcomes=new Map((Array.isArray(data?.outcomes)?data.outcomes:[]).map(o=>[o.setup_id,o]));$("setup-analysis-list").innerHTML=setups.length?setups.map(s=>{const o=outcomes.get(s.id),outcome=o?`${o.outcome} · MFE ${num(o.mfe_pct,3)}% · MAE ${num(o.mae_pct,3)}%`:"Без виртуального сопровождения",baselineValid=s.acceleration_baseline_valid!==false,acceleration=baselineValid?`${num(s.acceleration,2)}×`:"Недостаточно baseline",tape=`${money(s.acceleration_current_notional)} / ${money(s.acceleration_baseline_notional)}`;return `<article class="setup-card"><div class="setup-card-head"><div><b class="symbol">${esc(s.symbol)} · ${esc(s.side)}</b><small>${time(s.timestamp)} UTC · ${esc(reasonLabels[s.reason]||s.reason)}</small></div><span class="setup-decision ${s.decision==="ENTRY"?"entry":""}">${esc(s.decision)}</span></div><div class="setup-values"><div><span>Вход</span><b>${price(s.entry)}</b></div><div><span>Стоп</span><b>${price(s.stop)} (${num(s.stop_pct,3)}%)</b></div><div><span>Цель</span><b>${price(s.target)} (${num(s.target_pct,3)}%)</b></div><div><span>Net R/R</span><b>${num(s.net_rr,2)} / ${num(s.required_net_rr,2)}</b></div><div><span>Score</span><b>${s.score}/${s.score_required}</b></div><div><span>Издержки</span><b>${num(s.cost_pct,3)}%</b></div><div><span>Цель / издержки</span><b>${num(s.cost_coverage,2)}×</b></div><div><span>Стоп / издержки</span><b>${num(s.stop_cost_ratio,2)}×</b></div><div><span>Ускорение</span><b>${esc(acceleration)}</b></div><div><span>Лента сейчас / baseline</span><b>${esc(tape)}</b></div><div><span>Поглощено / исполнено</span><b>${num(s.absorption_depleted_quantity,2)} / ${num(s.absorption_executed_quantity,2)}</b></div><div><span>Размер стены нач. / текущ.</span><b>${num(s.absorption_initial_size,2)} / ${num(s.absorption_current_size,2)}</b></div><div><span>Matched ratio</span><b>${num(s.absorption_matched,2)}×</b></div><div><span>Дисбаланс</span><b>${num(s.imbalance,3)}</b></div></div><p class="setup-outcome">${esc(outcome)}</p></article>`}).join(""):'<div class="empty-block">Завершённых сетапов пока нет.</div>'}
function renderCounterfactuals(rows){rows=Array.isArray(rows)?rows:[];$("counterfactual-body").innerHTML=rows.length?rows.map(r=>`<tr><td class="symbol">${esc(r.variant_id)}</td><td>${Number(r.sample_size||0).toLocaleString("ru-RU")}</td><td>${num(Number(r.fill_rate||0)*100,1)}%</td><td><span class="positive">${Number(r.wins||0)} T</span> · <span class="negative">${Number(r.losses||0)} S</span> · ${Number(r.time_exits||0)} TIME · ${Number(r.data_gaps||0)} GAP</td><td class="${Number(r.average_net_r)>=0?"positive":"negative"}">${r.average_net_r==null?"—":num(r.average_net_r,3)}</td></tr>`).join(""):'<tr><td colspan="5" class="empty">Недостаточно завершённых сетапов.</td></tr>'}
async function refresh(){try{const r=await fetch("/api/snapshot",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);render(await r.json())}catch(_){$("error-banner").hidden=false;$("status-dot").className="status-dot offline";$("connection-label").textContent="Связь потеряна"}}
function tick(){$("clock").textContent=`${new Date().toLocaleTimeString("ru-RU",{hour12:false,timeZone:"UTC"})} UTC`}tick();refresh();setInterval(tick,1000);setInterval(refresh,1000);

const groups=[
  {id:"market",title:"Рынок и сканер",risk:"Базовые",desc:"Какие USDT perpetual-контракты попадут в активную группу.",fields:{force_demo:["Демо-данные","Использовать синтетический рынок вместо Bybit"],invert_sides:["Инвертировать paper-сделки","Тестировать противоположное направление исходного сигнала; live-торговля заблокирована"],demo_fallback:["Резервный демо-режим","Переключиться на демо, если Bybit недоступен"],scan_interval:["Интервал сканирования, сек","Повторный отбор ликвидных инструментов"],max_symbols:["Максимум монет","Top-N по обороту после применения фильтров; это не весь рынок"],min_turnover:["Минимальный оборот 24ч, USDT","Отсекает неликвидные контракты"],min_price:["Минимальная цена","Отсекает инструменты дешевле порога"],max_spread_pct:["Максимальный спред, %","Инструменты с большим спредом исключаются"],ws_chunk_size:["Монет в WebSocket-группе","Большие значения снижают число соединений, но увеличивают нагрузку"],demo_symbols:["Демо-монеты","Список тикеров через запятую"]}},
 {id:"risk",title:"Риск и портфель",risk:"Высокий риск",desc:"Лимиты капитала и защитные выключатели.",fields:{account_equity:["Виртуальный капитал, $","База для расчёта риска"],risk_per_trade_pct:["Риск на сделку, доля","0.0025 означает 0.25% капитала"],max_position_notional:["Макс. размер позиции, $","Жёсткий лимит номинала одной позиции"],max_open_positions:["Макс. открытых позиций","Общий лимит одновременных позиций"],max_daily_loss_pct:["Дневной стоп, доля","После достижения новые входы блокируются"],max_consecutive_losses:["Убытков подряд","Число убытков до защитной паузы"],cooldown_seconds:["Пауза после сделки, сек","Минимальный интервал перед новым входом"],loss_cooldown_seconds:["Пауза после убытка, сек","Увеличенная пауза после убыточной сделки"]}},
  {id:"execution",title:"Исполнение и выход",risk:"Экспертные",desc:"Общие комиссии, лимит удержания и сопровождение paper-позиций.",fields:{taker_fee_pct:["Комиссия тейкера, доля","0.0005 соответствует 0.05%"],slippage_pct:["Проскальзывание, доля","Консервативная поправка цены исполнения"],cost_safety_multiplier:["Запас стоимости","Множитель оценки полных издержек"],max_holding_seconds:["Макс. удержание, сек","Принудительный выход по времени"],trail_arm_r:["Включение трейлинга, R","Прибыль для активации сопровождения"],trail_giveback_r:["Допустимый откат, R","Сколько прибыли можно отдать после активации"],breakeven_arm_r:["Безубыток, R","Прибыль для переноса защиты к входу"],reversal_confirm_ticks:["Тиков разворота","Сколько подтверждений нужно для выхода"],reversal_confirm_seconds:["Время разворота, сек","Сколько секунд поток должен быть противоположным"],reversal_min_hold_seconds:["Мин. удержание до выхода, сек","Защита от закрытия сразу после входа"]}},
  {id:"strategy",title:"Режим стратегии",risk:"Экспертные",desc:"Выберите алгоритм входа. После сохранения перезапустите движок.",fields:{strategy_mode:["Режим","alternative: поглощение, пробой и ретест; fvg: возврат в fair value gap"]}},
  {id:"alternative",title:"Alternative",risk:"Экспертные",desc:"Настройки прежней логики: поглощённая стена, пробой и удержанный ретест.",fields:{alternative_wall_multiplier:["Множитель стены","Размер уровня относительно медианного объёма стакана"],alternative_signal_expiry_seconds:["Срок сигнала, сек","Сколько живёт сетап до ретеста"],alternative_retest_tolerance_pct:["Допуск ретеста, доля","Расстояние от уровня для подтверждения ретеста"],alternative_retest_hold_ticks:["Тиков удержания","Число последовательных подтверждений"],alternative_min_confluence_score:["Мин. оценка совпадений","Порог качества входа от 0 до 100"],alternative_min_net_reward_risk:["Мин. чистый R/R","Минимальное R/R после издержек"],alternative_target_r_multiple:["Цель, R","Расстояние цели в единицах риска"],alternative_max_target_pct:["Макс. цель, доля","Предельная дистанция динамической цели"],alternative_min_stop_pct:["Мин. стоп, доля","Нижняя граница стопа"],alternative_max_stop_pct:["Макс. стоп, доля","Верхняя граница стопа"],alternative_structure_buffer_pct:["Буфер структуры","Отступ стопа от поглощённого уровня"]}},
  {id:"fvg",title:"FVG · M15 → M1 → S5",risk:"Экспертные",desc:"M15 задаёт контекст, M1 подтверждает реакцию, S5 iFVG после инверсии и отдельного ретеста запускает вход.",fields:{fvg_m15_min_gap_atr:["M15: мин. FVG, ATR","Минимальная ширина контекстной зоны относительно ATR(14)"],fvg_m15_min_displacement_atr:["M15: displacement, ATR","Минимальный диапазон импульсной средней свечи"],fvg_m15_min_body_ratio:["M15: доля тела","Минимальная доля тела в диапазоне импульсной свечи"],fvg_m15_max_age_bars:["M15: срок зоны, свечей","Максимальный возраст нетестированного контекста"],fvg_m1_min_gap_atr:["M1: мин. FVG, ATR","Минимальная ширина подтверждающего FVG"],fvg_m1_min_displacement_atr:["M1: displacement, ATR","Минимальный диапазон подтверждающей средней свечи"],fvg_m1_min_body_ratio:["M1: доля тела","Минимальная доля тела M1 displacement"],fvg_m1_confirmation_bars:["M1: срок подтверждения","Сколько минут ждать новый направленный M1 FVG"],fvg_s5_min_gap_pct:["S5: мин. FVG, доля","Минимальный противоположный S5 FVG для инверсии"],fvg_s5_min_body_ratio:["S5: доля тела","Минимальная направленность S5 импульса"],fvg_s5_inversion_bars:["S5: срок инверсии","Сколько S5-свечей ждать закрытия за FVG"],fvg_s5_retest_bars:["S5: срок ретеста","Сколько S5-свечей ждать возврата в iFVG"],fvg_s5_entry_depth:["S5: глубина ретеста","0 = ближняя граница, 0.5 = середина, 1 = дальняя"],fvg_min_net_reward_risk:["Мин. чистый R/R","Минимальное R/R после издержек"],fvg_target_r_multiple:["Цель, R","Расстояние цели в единицах риска"],fvg_max_target_pct:["Макс. цель, доля","Предельная дистанция динамической цели"],fvg_min_stop_pct:["Мин. стоп, доля","Нижняя граница стопа"],fvg_max_stop_pct:["Макс. стоп, доля","Структурный стоп дальше порога отклоняет вход"],fvg_stop_buffer_pct:["Буфер iFVG стопа","Отступ стопа за дальней границей S5 iFVG"]}},
 {id:"readiness",title:"Готовность стратегии",risk:"Контроль",desc:"Критерии статистической готовности; live-торговля всё равно заблокирована.",fields:{min_live_trades:["Минимум сделок","Размер выборки для оценки"],min_live_profit_factor:["Мин. профит-фактор","Минимальная прибыльность выборки"],min_live_expectancy:["Мин. ожидание","Средний ожидаемый результат сделки"],max_live_drawdown_pct:["Макс. просадка, доля","Предельная допустимая просадка"]}}
];
let adminPassword="",loadedSettings=null,settingsDraft=null,settingsSection="strategy",settingsSearch="",aiRecommended={},aiManaged=new Set(),customDraft=null;
function api(path,options={}){return fetch(path,{...options,headers:{"content-type":"application/json","x-admin-password":adminPassword,...(options.headers||{})}}).then(async r=>{const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data})}
function sliderSpec(key,value){if(key.includes("_gap_atr")||key.includes("_displacement_atr"))return [.01,3,.01];if(key.includes("_body_ratio")||key==="fvg_s5_entry_depth")return [0,1,.01];if(key.includes("_age_bars")||key.includes("_confirmation_bars")||key.includes("_inversion_bars")||key.includes("_retest_bars"))return [1,120,1];if(key==="fvg_candle_seconds")return [60,3600,60];if(key.includes("score"))return [0,100,1];if(key.includes("ticks")||key.includes("max_symbols")||key.includes("max_open_positions")||key.includes("losses")||key.includes("trades"))return [0,Math.max(20,Math.ceil(value*3)),1];if(key.includes("seconds")||key.includes("interval"))return [0,Math.max(60,Math.ceil(value*3)),Math.max(1,value>=60?10:1)];if(key.includes("equity")||key.includes("notional")||key.includes("turnover"))return [0,Math.max(1000,Math.ceil(value*3)),Math.max(1,Math.ceil(value/100))];if(value<0.02)return [0,Math.max(.01,value*4),.0001];if(value<1)return [0,Math.max(1,value*4),.01];return [0,Math.max(10,Math.ceil(value*3)),.1]}
function formatSettingValue(key,value){if(key==="fvg_candle_seconds")return `${Number(value)/60} мин`;if(key.includes("seconds"))return `${Number(value).toLocaleString("ru-RU")} сек`;if(key.includes("pct")||key.includes("_depth"))return Number(value).toLocaleString("ru-RU",{maximumFractionDigits:4});return Number(value).toLocaleString("ru-RU",{maximumFractionDigits:4})}
function inputFor(key,value,label,help){const isBool=typeof value==="boolean",isList=Array.isArray(value),locked=settingsDraft.settings_profile==="ai_recommended"&&aiManaged.has(key),disabled=locked?"disabled":"",lock=locked?'<em class="ai-lock">AI</em>':"";if(key==="settings_profile")return `<article class="setting-row setting-select profile-select" data-search="${esc(`${label} ${help} ${key}`.toLowerCase())}"><div class="setting-row-copy"><b>${esc(label)}</b><small>${esc(help)}</small></div><select id="cfg-${key}" name="${key}"><option value="custom" ${value==="custom"?"selected":""}>Custom</option><option value="ai_recommended" ${value==="ai_recommended"?"selected":""}>AI Recommended · Static</option></select></article>`;if(key==="strategy_mode")return `<article class="setting-row setting-select" data-search="${esc(`${label} ${help} ${key}`.toLowerCase())}"><div class="setting-row-copy"><b>${esc(label)}</b><small>${esc(help)}</small></div><select id="cfg-${key}" name="${key}"><option value="alternative" ${value==="alternative"?"selected":""}>Alternative</option><option value="fvg" ${value==="fvg"?"selected":""}>FVG · M15 → M1 → S5</option></select></article>`;if(isBool)return `<article class="setting-row setting-check ${locked?"ai-managed":""}" data-search="${esc(`${label} ${help} ${key}`.toLowerCase())}"><div class="setting-row-copy"><b>${esc(label)}${lock}</b><small>${esc(help)}</small></div><label><input id="cfg-${key}" name="${key}" type="checkbox" ${value?"checked":""} ${disabled}><span>${value?"Включено":"Выключено"}</span></label></article>`;if(isList)return `<article class="setting-row setting-text ${locked?"ai-managed":""}" data-search="${esc(`${label} ${help} ${key}`.toLowerCase())}"><div class="setting-row-copy"><b>${esc(label)}${lock}</b><small>${esc(help)}</small></div><input id="cfg-${key}" name="${key}" type="text" value="${esc(value.join(", "))}" ${disabled}></article>`;const[min,max,step]=sliderSpec(key,value);return `<article class="setting-row setting-slider ${locked?"ai-managed":""}" data-search="${esc(`${label} ${help} ${key}`.toLowerCase())}"><div class="setting-row-copy"><b>${esc(label)}${lock}</b><small>${esc(help)}</small></div><input id="cfg-${key}" name="${key}" type="range" min="${min}" max="${max}" step="${step}" value="${value}" ${disabled}><output for="cfg-${key}">${esc(formatSettingValue(key,value))}</output></article>`}
function setDraftValue(key,el){const old=settingsDraft[key];if(typeof old==="boolean")settingsDraft[key]=el.checked;else if(Array.isArray(old))settingsDraft[key]=el.value.split(",").map(v=>v.trim().toUpperCase()).filter(Boolean);else if(typeof old==="number"){const parsed=Number(el.value);settingsDraft[key]=el.value.trim()!==""&&Number.isFinite(parsed)?parsed:old}else settingsDraft[key]=el.value}
function rowsFor(fields){return Object.entries(fields).filter(([key,[label,help]])=>!settingsSearch||`${key} ${label} ${help}`.toLowerCase().includes(settingsSearch)).map(([key,[label,help]])=>inputFor(key,settingsDraft[key],label,help))}
function splitColumns(rows){const middle=Math.ceil(rows.length/2);return `<div class="settings-column"><header><span>Настройки 01</span><button type="button" aria-label="Сортировка">⇅</button></header>${rows.slice(0,middle).join("")||`<p class="settings-empty">Ничего не найдено.</p>`}</div><div class="settings-column"><header><span>Настройки 02</span><button type="button" aria-label="Сортировка">⇅</button></header>${rows.slice(middle).join("")||`<p class="settings-empty">Ничего не найдено.</p>`}</div>`}
function bindSettingRows(root){root.querySelectorAll("input,select").forEach(el=>{const update=()=>{if(el.name==="settings_profile"){const profile=el.value;if(profile==="ai_recommended"){customDraft=structuredClone(settingsDraft);Object.assign(settingsDraft,aiRecommended);settingsDraft.settings_profile=profile}else{const strategy=settingsDraft.strategy_mode;settingsDraft=customDraft?structuredClone(customDraft):structuredClone(loadedSettings);settingsDraft.settings_profile=profile;settingsDraft.strategy_mode=strategy}const profileSummary=$("settings-summary").querySelector("strong");if(profileSummary)profileSummary.textContent=profile==="ai_recommended"?"AI":"CUSTOM";renderSettingsSection();return}setDraftValue(el.name,el);const row=el.closest(".setting-row");if(el.name==="strategy_mode"){if(customDraft)customDraft.strategy_mode=settingsDraft.strategy_mode;renderSettingsSection();return}if(el.type==="range")row.querySelector("output").textContent=formatSettingValue(el.name,settingsDraft[el.name]);if(el.type==="checkbox")row.querySelector("span").textContent=settingsDraft[el.name]?"Включено":"Выключено"};el.oninput=update;el.onchange=update})}
function renderSettingsSection(){const root=$("settings-groups"),telegram=$("telegram-panel"),nav=$("settings-nav");nav.querySelectorAll("button").forEach(button=>button.classList.toggle("active",button.dataset.section===settingsSection));telegram.hidden=settingsSection!=="telegram";if(settingsSection==="telegram"){root.innerHTML="";return}const group=settingsSection==="strategy"?groups.find(item=>item.id===settingsDraft.strategy_mode):groups.find(item=>item.id===settingsSection);const fields=settingsSection==="strategy"?{settings_profile:["Профиль настроек","Custom разрешает ручную настройку. AI Recommended использует зафиксированный пресет PulseBook."],strategy_mode:["Стратегия","Выбор алгоритма остаётся доступным в обоих профилях."],...group.fields}:group.fields;const notice=settingsDraft.settings_profile==="ai_recommended"?'<div class="ai-profile-notice"><b>AI Recommended</b><span>Стратегические и риск-параметры зафиксированы в коде. Чтобы редактировать их вручную, выберите Custom.</span></div>':"";root.innerHTML=`<section class="settings-group"><header class="settings-group-head"><p class="setting-kicker">${esc(settingsSection==="strategy"?"СТРАТЕГИЯ":"КОНФИГУРАЦИЯ")}</p><h3>${esc(group.title)}</h3><p class="muted">${esc(group.desc)}</p></header>${notice}<div class="settings-columns">${splitColumns(rowsFor(fields))}</div></section>`;bindSettingRows(root)}
function drawSettings(settings,status){aiRecommended=structuredClone(settings._ai_recommended||{});aiManaged=new Set(settings._ai_managed_keys||[]);const savedCustom=structuredClone(settings._custom_settings||{}),clean=structuredClone(settings);delete clean._ai_recommended;delete clean._ai_managed_keys;delete clean._custom_settings;loadedSettings=structuredClone(clean);settingsDraft=structuredClone(clean);customDraft=structuredClone(clean);Object.assign(customDraft,savedCustom);customDraft.settings_profile="custom";settingsSection="strategy";settingsSearch="";$("settings-search").value="";$("settings-summary").innerHTML=`<div><span>Профиль</span><strong>${settingsDraft.settings_profile==="ai_recommended"?"AI":"CUSTOM"}</strong></div><div><span>Стратегия</span><strong>${esc(status.strategy_mode||settings.strategy_mode)}</strong></div>`;const sections=[{id:"strategy",label:"Стратегия",icon:"⌘",group:"РЕЖИМ"},{id:"market",label:"Рынок и сканер",icon:"⌁",group:"ТОРГОВЛЯ"},{id:"risk",label:"Риск и лимиты",icon:"◇",group:"ТОРГОВЛЯ"},{id:"execution",label:"Исполнение",icon:"↗",group:"ТОРГОВЛЯ"},{id:"readiness",label:"Готовность",icon:"◌",group:"СИСТЕМА"},{id:"telegram",label:"Telegram",icon:"◒",group:"СИСТЕМА"}];let last="";$("settings-nav").innerHTML=sections.map(section=>`${section.group!==last?(last=section.group,`<p>${section.group}</p>`):""}<button type="button" data-section="${section.id}"><span class="nav-icon">${section.icon}</span>${section.label}</button>`).join("");$("settings-nav").querySelectorAll("button").forEach(button=>button.onclick=()=>{settingsSection=button.dataset.section;renderSettingsSection()});renderSettingsSection()}
async function loginSettings(){adminPassword=$("admin-password").value;$("settings-message").textContent="Загрузка…";try{const [settings,status]=await Promise.all([api("/api/admin/settings"),fetch("/api/settings/status").then(r=>r.json())]);$("auth-panel").hidden=true;$("settings-workspace").hidden=false;drawSettings(settings,status);await loadTelegramStatus();$("settings-message").textContent=""}catch(e){$("settings-message").textContent=e.message}}
function collectSettings(){return structuredClone(settingsDraft)}
$("diagnostics-export").onclick=async()=>{if(!adminPassword)adminPassword=prompt("Пароль администратора для экспорта диагностики")||"";if(!adminPassword)return;const button=$("diagnostics-export"),label=button.textContent;button.disabled=true;button.textContent="Подготовка…";try{const response=await fetch("/api/admin/diagnostics/export",{headers:{"x-admin-password":adminPassword}});if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.error||`HTTP ${response.status}`)}const blob=await response.blob(),url=URL.createObjectURL(blob),link=document.createElement("a");link.href=url;link.download=`pulsebook-diagnostics-${new Date().toISOString().replace(/[:.]/g,"-")}.json`;document.body.appendChild(link);link.click();link.remove();URL.revokeObjectURL(url)}catch(error){alert(error.message)}finally{button.disabled=false;button.textContent=label}};
$("settings-open").onclick=()=>$("settings-dialog").showModal();$("settings-menu").onclick=()=>$("settings-dialog").classList.toggle("sidebar-collapsed");$("settings-search").oninput=e=>{settingsSearch=e.target.value.trim().toLowerCase();if(settingsDraft)renderSettingsSection()};$("settings-login").onclick=loginSettings;$("admin-password").onkeydown=e=>{if(e.key==="Enter"&&!e.isComposing&&e.keyCode!==229)loginSettings()};$("settings-reset").onclick=()=>{settingsDraft=loadedSettings.settings_profile==="ai_recommended"?structuredClone(loadedSettings):structuredClone(customDraft);renderSettingsSection();$("settings-message").textContent="Изменения сброшены"};$("settings-form").onsubmit=async e=>{e.preventDefault();$("settings-message").textContent="Сохранение...";try{const result=await api("/api/admin/settings",{method:"PUT",body:JSON.stringify(collectSettings())});if(settingsDraft.settings_profile==="custom")customDraft=structuredClone(settingsDraft);loadedSettings=structuredClone(settingsDraft);$("settings-message").textContent=result.message;$("settings-restart").hidden=false}catch(error){$("settings-message").textContent=error.message}};$("settings-restart").onclick=async()=>{if(!confirm("Перезапустить движок сейчас? Соединение прервётся на несколько секунд."))return;$("settings-restart").disabled=true;try{await api("/api/admin/restart",{method:"POST",body:"{}"});$("settings-message").textContent="Перезапуск...";setTimeout(()=>location.reload(),4000)}catch(error){$("settings-message").textContent=error.message;$("settings-restart").disabled=false}};
async function loadTelegramStatus(){if(!adminPassword)return;try{const status=await api("/api/admin/telegram/status");const text=$("telegram-status-text");text.textContent=status.enabled?"Telegram: включены":"Telegram: отключены";text.style.color=status.enabled?"var(--accent)":"var(--muted)"}catch{}}$("telegram-toggle").onclick=async()=>{if(!adminPassword)return;const button=$("telegram-toggle");button.disabled=true;try{const current=await api("/api/admin/telegram/status");const result=await api("/api/admin/telegram/toggle",{method:"POST",body:JSON.stringify({enabled:!current.enabled})});$("settings-message").textContent=result.message;await loadTelegramStatus()}catch(error){$("settings-message").textContent=error.message}finally{button.disabled=false}};

let heatmapMode=false,heatmapSymbol="",heatmapRange="3d",heatmapRadar=[],heatmapData=null,heatmapRequest=0;
const compactMoney=(value)=>`$${Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(Number(value)||0)}`;

function syncHeatmapCoins(radar){
  heatmapRadar=radar;
  $("heatmap-coin-count").textContent=String(radar.length).padStart(2,"0");
  $("heatmap-coins").innerHTML=radar.length?radar.map(item=>{const symbol=String(item.symbol||"");return `<button type="button" class="coin-row ${symbol===heatmapSymbol?"active":""}" data-symbol="${esc(symbol)}"><span><b>${esc(symbol.replace(/USDT$/,""))}</b><small>/ USDT</small></span><strong>${price(item.price??item.mid)}</strong></button>`}).join(""):'<div class="empty-block">Активная группа пока пуста.</div>';
  $("heatmap-coins").querySelectorAll("button").forEach(button=>button.onclick=()=>selectHeatmapSymbol(button.dataset.symbol));
}

function setDashboardMode(mode){
  heatmapMode=mode==="heatmap";
  document.querySelectorAll(".mode-switch button").forEach(button=>button.classList.toggle("active",button.dataset.mode===mode));
  document.querySelectorAll(".overview-section").forEach(section=>section.hidden=heatmapMode);
  $("heatmap-view").hidden=!heatmapMode;
  if(heatmapMode&&!heatmapSymbol&&heatmapRadar.length)selectHeatmapSymbol(heatmapRadar[0].symbol);
  else if(heatmapMode&&heatmapData)requestAnimationFrame(drawHeatmap);
}

function selectHeatmapSymbol(symbol){
  if(!symbol)return;
  heatmapSymbol=symbol;
  syncHeatmapCoins(heatmapRadar);
  $("heatmap-symbol").textContent=symbol;
  loadHeatmap();
}

async function loadHeatmap(){
  if(!heatmapSymbol)return;
  const request=++heatmapRequest;
  $("heatmap-status").textContent="ЗАГРУЗКА";
  $("heatmap-message").hidden=false;
  $("heatmap-message").textContent="Получение уровней ликвидаций Coinglass...";
  $("heatmap-canvas-wrap").hidden=true;
  try{
    const response=await fetch(`/api/coinglass/liquidation-heatmap?symbol=${encodeURIComponent(heatmapSymbol)}&range=${encodeURIComponent(heatmapRange)}`,{cache:"no-store"});
    const data=await response.json().catch(()=>({}));
    if(!response.ok)throw new Error(data.error||`HTTP ${response.status}`);
    if(request!==heatmapRequest)return;
    heatmapData=data;
    $("heatmap-message").hidden=true;
    $("heatmap-canvas-wrap").hidden=false;
    $("heatmap-status").textContent=`COINGLASS · ${String(data.range).toUpperCase()}`;
    renderLargestLiquidations(data.largest_liquidations);
    requestAnimationFrame(drawHeatmap);
  }catch(error){
    if(request!==heatmapRequest)return;
    heatmapData=null;
    $("heatmap-status").textContent="НЕТ ДАННЫХ";
    $("heatmap-message").hidden=false;
    $("heatmap-message").textContent=error.message;
    $("largest-liquidations").innerHTML='<div class="empty-block">Кластеры недоступны.</div>';
  }
}

function renderLargestLiquidations(rows){
  rows=Array.isArray(rows)?rows:[];
  $("largest-liquidations").innerHTML=rows.length?rows.map((row,index)=>`<div class="liquidation-row"><span class="cluster-rank">${String(index+1).padStart(2,"0")}</span><span><b>${price(row.price)}</b><small class="${row.side==="LONG"?"negative":"positive"}">${row.side==="LONG"?"LONG LIQUIDATIONS":"SHORT LIQUIDATIONS"}</small></span><strong>${compactMoney(row.amount)}</strong></div>`).join(""):'<div class="empty-block">Крупные кластеры не найдены.</div>';
}

function drawHeatmap(){
  if(!heatmapData||$("heatmap-canvas-wrap").hidden)return;
  const canvas=$("heatmap-canvas"),wrap=$("heatmap-canvas-wrap"),width=Math.max(320,wrap.clientWidth),height=Math.max(420,Math.min(620,width*.56)),dpr=Math.min(window.devicePixelRatio||1,2);
  canvas.width=Math.floor(width*dpr);canvas.height=Math.floor(height*dpr);canvas.style.width=`${width}px`;canvas.style.height=`${height}px`;
  const ctx=canvas.getContext("2d");ctx.scale(dpr,dpr);
  const margin={top:24,right:74,bottom:38,left:14},plotW=width-margin.left-margin.right,plotH=height-margin.top-margin.bottom;
  const candles=Array.isArray(heatmapData.price_candlesticks)?heatmapData.price_candlesticks:[],levels=(Array.isArray(heatmapData.y_axis)?heatmapData.y_axis:[]).map(Number),points=Array.isArray(heatmapData.liquidation_leverage_data)?heatmapData.liquidation_leverage_data:[];
  if(!candles.length||!levels.length)return;
  const lows=candles.map(row=>Number(row[3])),highs=candles.map(row=>Number(row[2])),minPrice=Math.min(...levels,...lows),maxPrice=Math.max(...levels,...highs),priceSpan=Math.max(maxPrice-minPrice,1e-9),xAt=index=>margin.left+(index/Math.max(candles.length-1,1))*plotW,yAt=value=>margin.top+(maxPrice-Number(value))/priceSpan*plotH;
  ctx.fillStyle="#090b0d";ctx.fillRect(0,0,width,height);
  ctx.strokeStyle="#20262b";ctx.lineWidth=1;ctx.fillStyle="#707981";ctx.font="10px ui-monospace, monospace";ctx.textAlign="left";
  for(let i=0;i<=5;i++){const y=margin.top+plotH*i/5,value=maxPrice-priceSpan*i/5;ctx.beginPath();ctx.moveTo(margin.left,y);ctx.lineTo(margin.left+plotW,y);ctx.stroke();ctx.fillText(price(value),margin.left+plotW+8,y+3)}
  const maxAmount=Math.max(1,...points.map(point=>Number(point[2])||0)),cellW=Math.max(1.2,plotW/Math.max(candles.length,1)*1.25),cellH=Math.max(2,plotH/Math.max(levels.length,1)*1.6);
  for(const point of points){const x=Number(point[0]),yIndex=Number(point[1]),amount=Number(point[2]);if(!Number.isFinite(x)||!Number.isFinite(yIndex)||!Number.isFinite(amount)||!levels[yIndex])continue;const intensity=Math.log1p(amount)/Math.log1p(maxAmount),hue=205-intensity*165;ctx.fillStyle=`hsla(${hue},92%,${42+intensity*18}%,${.1+intensity*.72})`;ctx.fillRect(xAt(x)-cellW/2,yAt(levels[yIndex])-cellH/2,cellW,cellH)}
  const candleW=Math.max(1,Math.min(6,plotW/Math.max(candles.length,1)*.58));
  candles.forEach((row,index)=>{const open=Number(row[1]),high=Number(row[2]),low=Number(row[3]),close=Number(row[4]),x=xAt(index),up=close>=open;ctx.strokeStyle=up?"#73d7a2":"#f0786f";ctx.fillStyle=up?"#73d7a2":"#f0786f";ctx.globalAlpha=.86;ctx.beginPath();ctx.moveTo(x,yAt(high));ctx.lineTo(x,yAt(low));ctx.stroke();ctx.fillRect(x-candleW/2,Math.min(yAt(open),yAt(close)),candleW,Math.max(1,Math.abs(yAt(open)-yAt(close))));ctx.globalAlpha=1});
  const largest=Array.isArray(heatmapData.largest_liquidations)?heatmapData.largest_liquidations.slice(0,5):[];
  ctx.setLineDash([4,4]);ctx.font="700 10px ui-monospace, monospace";
  largest.forEach((row,index)=>{const y=yAt(row.price);ctx.strokeStyle=index===0?"#fff1a8":"rgba(255,220,100,.62)";ctx.beginPath();ctx.moveTo(margin.left,y);ctx.lineTo(margin.left+plotW,y);ctx.stroke();ctx.fillStyle=index===0?"#fff1a8":"#d8c476";ctx.textAlign="right";ctx.fillText(`${index+1} · ${compactMoney(row.amount)}`,margin.left+plotW-6,y-5)});ctx.setLineDash([]);
  const last=candles[candles.length-1],lastPrice=Number(last[4]),lastY=yAt(lastPrice);ctx.fillStyle="#f2f1ec";ctx.fillRect(margin.left+plotW,lastY-8,70,16);ctx.fillStyle="#0b0d0f";ctx.textAlign="left";ctx.fillText(price(lastPrice),margin.left+plotW+5,lastY+3);
  ctx.fillStyle="#707981";ctx.textAlign="center";for(let i=0;i<4;i++){const index=Math.round((candles.length-1)*i/3),date=new Date(Number(candles[index][0])*1000);ctx.fillText(date.toLocaleDateString("ru-RU",{day:"2-digit",month:"short",timeZone:"UTC"}),xAt(index),height-13)}
}

document.querySelectorAll(".mode-switch button").forEach(button=>button.onclick=()=>setDashboardMode(button.dataset.mode));
$("heatmap-ranges").querySelectorAll("button").forEach(button=>button.onclick=()=>{heatmapRange=button.dataset.range;$("heatmap-ranges").querySelectorAll("button").forEach(item=>item.classList.toggle("active",item===button));if(heatmapSymbol)loadHeatmap()});
window.addEventListener("resize",()=>{if(heatmapMode&&heatmapData)requestAnimationFrame(drawHeatmap)});
setInterval(()=>{if(heatmapMode&&heatmapSymbol)loadHeatmap()},60000);
