"use strict";
const $=(id)=>document.getElementById(id);const esc=(v)=>String(v??"").replace(/[&<>"']/g,(c)=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const num=(v,d=2)=>Number(v||0).toLocaleString("en-US",{minimumFractionDigits:d,maximumFractionDigits:d});const money=(v)=>`${Number(v||0)<0?"-":""}$${num(Math.abs(Number(v||0)),2)}`;const price=(v)=>Number(v||0).toLocaleString("en-US",{maximumFractionDigits:Number(v)<1?6:2});
const duration=(s)=>{s=Math.max(0,Math.floor(Number(s)||0));return [Math.floor(s/3600),Math.floor(s%3600/60),s%60].map(v=>String(v).padStart(2,"0")).join(":")};const time=(ts)=>ts?new Date(ts*1000).toLocaleTimeString("en-GB",{hour:"2-digit",minute:"2-digit",second:"2-digit",timeZone:"UTC"}):"—";
function tone(el,v){el.classList.remove("positive","negative");if(Number(v)>0)el.classList.add("positive");if(Number(v)<0)el.classList.add("negative")}
function render(s){const st=s.stats||{};$("pnl").textContent=money(st.pnl);tone($("pnl"),st.pnl);$("pnl-note").textContent=`Реализовано ${money(st.realized)} · Открыто ${money(st.unrealized)}`;$("win-rate").textContent=`${num(st.win_rate,1)}%`;$("record").textContent=`${st.wins||0} побед / ${st.losses||0} убытков`;$("profit-factor").textContent=Number.isFinite(Number(st.profit_factor))?num(st.profit_factor):"∞";$("trades").textContent=`${st.trades||0} закрытых сделок`;$("open-count").textContent=String(st.open||0).padStart(2,"0");$("uptime").textContent=`Работает ${duration(s.uptime)}`;$("session").textContent=s.session?`#${s.session}`:"—";$("mode").textContent=String(s.mode||"PAPER").toUpperCase();$("source-badge").textContent=`ИСТОЧНИК ${String(s.source||"—").toUpperCase()}`;$("last-update").textContent=`ОБНОВЛЕНО ${time(s.timestamp)} UTC`;
const radar=Array.isArray(s.radar)?s.radar:[];$("symbols-count").textContent=String(radar.length);$("radar-body").innerHTML=radar.length?radar.slice(0,20).map(r=>{const flow=Number(r.imbalance??r.delta??r.flow??0);const signal=r.signal||r.status||"MONITOR";return `<tr><td class="symbol">${esc(r.symbol)}</td><td>${price(r.price??r.mid)}</td><td>${num(r.spread_pct??r.spread,3)}%</td><td class="${flow>0?"positive":flow<0?"negative":""}">${flow>0?"+":""}${num(flow,2)}</td><td><span class="signal">${esc(signal)}</span></td></tr>`}).join(""):'<tr><td colspan="5" class="empty">Инструменты ещё не получены. Идёт инициализация сканера.</td></tr>';
const positions=Array.isArray(s.positions)?s.positions:[];$("position-count").textContent=String(positions.length).padStart(2,"0");$("positions").innerHTML=positions.length?positions.map(p=>`<article class="position"><div><span>ИНСТРУМЕНТ</span><b class="symbol">${esc(p.symbol)} · <i class="side ${p.side==="LONG"?"positive":"negative"}">${esc(p.side)}</i></b></div><div><span>ВХОД</span><b>${price(p.entry)}</b></div><div><span>ТЕКУЩАЯ</span><b>${price(p.mark)}</b></div><div><span>СТОП / ЦЕЛЬ</span><b>${price(p.stop_price)} / ${price(p.target_price)}</b></div><div><span>НЕРЕАЛИЗ. P&L</span><b class="${Number(p.unrealized)>=0?"positive":"negative"}">${money(p.unrealized)}</b></div></article>`).join(""):'<div class="empty-block">Открытых позиций нет. Движок ищет подходящие сетапы.</div>';
const logs=Array.isArray(s.logs)?s.logs:[];$("event-count").textContent=String(logs.length).padStart(2,"0");$("logs").innerHTML=logs.length?logs.slice(0,30).map(l=>`<article class="event ${esc(String(l.level||"").toLowerCase())}"><div class="event-head"><span>${esc(l.symbol||"SYSTEM")}</span><time>${time(l.timestamp)} UTC</time></div><p>${esc(l.message)}</p></article>`).join(""):'<div class="empty-block">Событий пока нет. Здесь появится телеметрия движка.</div>';
const trades=Array.isArray(s.closed_trades)?s.closed_trades:[];$("trades-body").innerHTML=trades.length?trades.slice(0,20).map(t=>`<tr><td>${time(t.closed_at)} UTC</td><td class="symbol">${esc(t.symbol)}</td><td class="side ${t.side==="LONG"?"positive":"negative"}">${esc(t.side)}</td><td>${price(t.entry)} → ${price(t.exit)}</td><td class="${Number(t.pnl)>=0?"positive":"negative"}">${money(t.pnl)}</td><td>${esc(t.reason)}</td></tr>`).join(""):'<tr><td colspan="6" class="empty">В этой сессии нет закрытых сделок.</td></tr>';
$("error-banner").hidden=true;$("status-dot").className="status-dot online";$("connection-label").textContent="Связь установлена"}
async function refresh(){try{const r=await fetch("/api/snapshot",{cache:"no-store"});if(!r.ok)throw new Error(`HTTP ${r.status}`);render(await r.json())}catch(_){$("error-banner").hidden=false;$("status-dot").className="status-dot offline";$("connection-label").textContent="Связь потеряна"}}
function tick(){$("clock").textContent=`${new Date().toLocaleTimeString("ru-RU",{hour12:false,timeZone:"UTC"})} UTC`}tick();refresh();setInterval(tick,1000);setInterval(refresh,1000);

const groups=[
 {id:"market",title:"Рынок и сканер",risk:"Базовые",desc:"Какие USDT perpetual-контракты попадут в активную группу.",fields:{force_demo:["Демо-данные","Использовать синтетический рынок вместо Bybit"],demo_fallback:["Резервный демо-режим","Переключиться на демо, если Bybit недоступен"],scan_interval:["Интервал сканирования, сек","Повторный отбор ликвидных инструментов"],max_symbols:["Максимум монет","Top-N по обороту после применения фильтров; это не весь рынок"],min_turnover:["Минимальный оборот 24ч, USDT","Отсекает неликвидные контракты"],min_price:["Минимальная цена","Отсекает инструменты дешевле порога"],max_spread_pct:["Максимальный спред, %","Инструменты с большим спредом исключаются"],ws_chunk_size:["Монет в WebSocket-группе","Большие значения снижают число соединений, но увеличивают нагрузку"],demo_symbols:["Демо-монеты","Список тикеров через запятую"]}},
 {id:"risk",title:"Риск и портфель",risk:"Высокий риск",desc:"Лимиты капитала и защитные выключатели.",fields:{account_equity:["Виртуальный капитал, $","База для расчёта риска"],risk_per_trade_pct:["Риск на сделку, доля","0.0025 означает 0.25% капитала"],max_position_notional:["Макс. размер позиции, $","Жёсткий лимит номинала одной позиции"],max_open_positions:["Макс. открытых позиций","Общий лимит одновременных позиций"],max_daily_loss_pct:["Дневной стоп, доля","После достижения новые входы блокируются"],max_consecutive_losses:["Убытков подряд","Число убытков до защитной паузы"],cooldown_seconds:["Пауза после сделки, сек","Минимальный интервал перед новым входом"],loss_cooldown_seconds:["Пауза после убытка, сек","Увеличенная пауза после убыточной сделки"]}},
 {id:"execution",title:"Исполнение и выход",risk:"Экспертные",desc:"Модель комиссий, стопов и сопровождения paper-позиций.",fields:{taker_fee_pct:["Комиссия тейкера, доля","0.0005 соответствует 0.05%"],slippage_pct:["Проскальзывание, доля","Консервативная поправка цены исполнения"],cost_safety_multiplier:["Запас стоимости","Множитель оценки полных издержек"],min_net_reward_risk:["Мин. чистый R/R","Минимальное отношение доходности к риску после издержек"],target_r_multiple:["Цель, R","Расстояние цели в единицах риска"],min_stop_pct:["Мин. стоп, доля","Нижняя граница стопа"],max_stop_pct:["Макс. стоп, доля","Верхняя граница стопа"],structure_buffer_pct:["Буфер структуры","Отступ стопа от поглощённого уровня"],trail_arm_r:["Включение трейлинга, R","Прибыль для активации сопровождения"],trail_giveback_r:["Допустимый откат, R","Сколько прибыли можно отдать после активации"],breakeven_arm_r:["Безубыток, R","Прибыль для переноса защиты к входу"]}},
 {id:"signal",title:"Сигнал и подтверждение",risk:"Экспертные",desc:"Чувствительность последовательности поглощение — пробой — ретест.",fields:{wall_multiplier:["Множитель стены","Размер уровня относительно медианного объёма стакана"],signal_expiry_seconds:["Срок сигнала, сек","Сколько живёт неподтверждённый сетап"],retest_tolerance_pct:["Допуск ретеста, доля","Расстояние от уровня для подтверждения ретеста"],retest_hold_ticks:["Тиков удержания","Число последовательных подтверждений"],min_confluence_score:["Мин. оценка совпадений","Порог качества входа от 0 до 100"]}},
 {id:"readiness",title:"Готовность стратегии",risk:"Контроль",desc:"Критерии статистической готовности; live-торговля всё равно заблокирована.",fields:{min_live_trades:["Минимум сделок","Размер выборки для оценки"],min_live_profit_factor:["Мин. профит-фактор","Минимальная прибыльность выборки"],min_live_expectancy:["Мин. ожидание","Средний ожидаемый результат сделки"],max_live_drawdown_pct:["Макс. просадка, доля","Предельная допустимая просадка"]}}
];
let adminPassword="",loadedSettings=null;
function api(path,options={}){return fetch(path,{...options,headers:{"content-type":"application/json","x-admin-password":adminPassword,...(options.headers||{})}}).then(async r=>{const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||`HTTP ${r.status}`);return data})}
function inputFor(key,value,label,help){const isBool=typeof value==="boolean",isList=Array.isArray(value);if(isBool)return `<div class="setting-field checkbox"><input id="cfg-${key}" name="${key}" type="checkbox" ${value?"checked":""}><div><label for="cfg-${key}">${esc(label)}</label><small>${esc(help)}</small></div></div>`;return `<div class="setting-field"><label for="cfg-${key}">${esc(label)}<code>${esc(key)}</code></label><input id="cfg-${key}" name="${key}" type="${typeof value==="number"?"number":"text"}" ${typeof value==="number"?'step="any"':''} value="${esc(isList?value.join(", "):value)}"><small>${esc(help)}</small></div>`}
function drawSettings(settings,status){loadedSettings=structuredClone(settings);$("settings-summary").innerHTML=`<div><span>Режим</span><strong>${esc(status.mode||settings.trading_mode)}</strong></div><div><span>Источник</span><strong>${esc(status.source||"—")}</strong></div><div><span>Активно монет</span><strong>${status.active_symbols||0} / ${settings.max_symbols}</strong></div><div><span>Live-торговля</span><strong>Заблокирована</strong></div>`;$("settings-nav").innerHTML=groups.map(g=>`<button type="button" data-target="${g.id}">${g.title}</button>`).join("");$("settings-groups").innerHTML=groups.map(g=>`<section class="settings-group" id="group-${g.id}"><header class="settings-group-head"><h3>${g.title}<span class="risk-badge">${g.risk}</span></h3><p class="muted">${g.desc}</p></header><div class="fields-grid">${Object.entries(g.fields).map(([key,[label,help]])=>inputFor(key,settings[key],label,help)).join("")}</div></section>`).join("");$("settings-nav").querySelectorAll("button").forEach(b=>b.onclick=()=>$("group-"+b.dataset.target).scrollIntoView({behavior:"smooth"}));}
async function loginSettings(){adminPassword=$("admin-password").value;$("settings-message").textContent="Загрузка…";try{const [settings,status]=await Promise.all([api("/api/admin/settings"),fetch("/api/settings/status").then(r=>r.json())]);$("auth-panel").hidden=true;$("settings-workspace").hidden=false;drawSettings(settings,status);$("settings-message").textContent=""}catch(e){$("settings-message").textContent=e.message}}
function collectSettings(){const next=structuredClone(loadedSettings);for(const group of groups)for(const key of Object.keys(group.fields)){const el=$("cfg-"+key);if(!el)continue;const old=next[key];if(typeof old==="boolean"){next[key]=el.checked}else if(Array.isArray(old)){next[key]=el.value.split(",").map(v=>v.trim().toUpperCase()).filter(Boolean)}else if(typeof old==="number"){const parsed=Number(el.value);next[key]=el.value.trim()!==""&&Number.isFinite(parsed)?parsed:old}else{next[key]=el.value}}return next}
$("settings-open").onclick=()=>$("settings-dialog").showModal();$("settings-close").onclick=()=>$("settings-dialog").close();$("settings-login").onclick=loginSettings;$("admin-password").onkeydown=e=>{if(e.key==="Enter"&&!e.isComposing&&e.keyCode!==229)loginSettings()};$("settings-reset").onclick=()=>loadedSettings&&drawSettings(loadedSettings,{mode:loadedSettings.trading_mode});$("settings-form").onsubmit=async e=>{e.preventDefault();$("settings-message").textContent="Сохранение…";try{const result=await api("/api/admin/settings",{method:"PUT",body:JSON.stringify(collectSettings())});$("settings-message").textContent=result.message;$("settings-restart").hidden=false}catch(error){$("settings-message").textContent=error.message}};$("settings-restart").onclick=async()=>{if(!confirm("Перезапустить движок сейчас? Соединение прервётся на несколько секунд."))return;try{await api("/api/admin/restart",{method:"POST",body:"{}"});$("settings-message").textContent="Перезапуск…";setTimeout(()=>location.reload(),4000)}catch(error){$("settings-message").textContent=error.message}};
